Alertas Dinamicos aos Usuários
UNIVALI-LITE/Portugol-Studio pull request #875
Opened 2020-11-10 04:09 UTC by AdsonEsteves

# Resumo

A principal ideia deste pull request é de permitir que os usuários de mac possam receber alertas da necessidade de dar ao Portugol Studio acesso ao disco e "resolver" por enquanto o problema.

Para isso criei a solução de gerar "Alertas/Avisos" a versões específicas do Portugol dinâmicamente caso algum erro de atualização com o OS ocorra sem podermos verificar e o usuário possa solucionar como no caso do mac atualmente.

# Como funciona

Um json com uma lista de alertas estará na nuvem. Pode ser tanto como um arquivo aqui no repositório ou em outro local.
Como teste neste pull estou usando [este](https://cdn.discordapp.com/attachments/354074984857206794/775553082716454952/alertaseavisos.json)
A estrutura do json está assim:
```
{
	"alertas&avisos": [
		{
			"id": "idmensagem",
			"tipo": "Alerta",
			"OS": ["win", "linux", "os x"],
			"versao": ["2.7.4"],
			"titulo": "titulo",
			"subtitulo": "subtitulo",
			"mensagem": "mensagem",
			"link" : "link"
		}
	]
}

```

Analisando o computador que o usuario está e sua versão do Portugol é possível mandar alertas especificos para ele.
Quando o usuario abrir o Portugol a seguinte tela aparece:
![image](https://user-images.githubusercontent.com/8836540/98626329-43cdfa80-22f0-11eb-9aad-6f04fc3ea060.png)

Ao final da tela tem um checkbox que permite o usuario não receber mais essas mensagens no inicio do Portugol.
Quando ele assinala, os IDs das mensagens são registrados no computador dele. Quando ele abrir o Portugol, ele ignorará todas as mensagens cujo o ID esteja registrado no computador.
Assim, caso uma nova mensagem seja necessária ser enviada, basta mandar ela com um novo ID unico.

# Próximos passos
Criar um tutorial pros usuários de mac descobrirem como dar permissão de acesso ao disco para o Portugol.

# Dicas?
Bom se tiverem alguma dica pra melhorar o sistema, por favor mandem. Ou melhor, commitem.
Alguma outra tag de identificação seria interessante? Algum outro componente pra tela de alerta? refazer o design?
help pls (◕‿◕✿)

2020-11-10 13:55 UTC, AlissonSteffens commented
Porque que tem alerta e aviso escrito ali? é um alerta ou um aviso?

2020-11-10 16:50 UTC, AdsonEsteves commented
@AlissonSteffens 
Ah sim, estava pensando em colocar o tipo Aviso, onde a cor mudaria pra não ser tão urgente.
Mas estou em duvida se vale a pena.

2020-11-11 01:06 UTC, AdsonEsteves commented
Utilizando com [esse arquivo](https://cdn.discordapp.com/attachments/354074984857206794/775879353748946944/alertaseavisos.json)

![image](https://user-images.githubusercontent.com/8836540/98752303-b0a0cd80-23a0-11eb-911a-b1ac8b6626e8.png)

2020-11-11 16:59 UTC, Rafaelfcosta commented
É uma boa maneira de alertar os usuários, só espero que eles não ignorem e fechem sem ler.
Só pude testar no windows por estar sem vm do mac.

Na janelinha que abre avisando do link tem uns pequenos typos
![image](https://user-images.githubusercontent.com/21344756/98840546-b12f7780-2425-11eb-81d4-ffbfcaef2461.png)

2020-11-11 17:55 UTC, AdsonEsteves commented
@Rafaelfcosta  vlw
Bom, é por isso que deixei um vermelho bem grande ali :v
Vou dar uma olhada nessa janelinha

2020-11-11 22:31 UTC, AdsonEsteves commented
Mudei o tamanho de umas fontes da tela
![image](https://user-images.githubusercontent.com/8836540/98871939-81e42f00-2454-11eb-8c0d-fff7845e4cc0.png)

2020-11-12 14:31 UTC, AlissonSteffens commented
eu ainda acho que se está escrito alerta no título, e tem uma mensagem em vermelho, não faz sentido essa aba de alerta ali na janela. A não ser que ideia seja mostrar todos os alertas em uma única janela. Se for isso, acho que pode ser perigoso, a pessoa pode ler o primeiro e fechar a janela. acho que deveria ser uma para cada.

2020-11-12 16:42 UTC, AdsonEsteves commented
@AlissonSteffens 
Interessante, vou ver isso.

2020-11-12 18:15 UTC, noschang commented
> @AlissonSteffens
> Interessante, vou ver isso.

@AdsonEsteves, além do que o Alisson falou, pode ser interessante dar uma opção ao usuário de exibir novamente esses alertas. 

Pode ser que na hora o usuário tava com pressa e não leu, mas mesmo assim marcou a opção **"Li os avisos e não quero que apareçam novamente"**. Daí depois o usuário percebeu que deveria ter lido, mas não consegue mais acessar os avisos.

Talvez um botão discreto na interface

2020-11-13 00:11 UTC, AdsonEsteves commented
@AlissonSteffens 
@noschang 

![image](https://user-images.githubusercontent.com/8836540/99011726-7dd71080-252b-11eb-99f1-aebc7a18f871.png)

2020-11-13 13:02 UTC, AlissonSteffens requested changes
1) o arquivo de alertas está vindo de um upload no discord? acho que deveria estar no git este arquivo.
2) o link está levando para uma issue. Ela está bem explicada e tudo, mas acho que não faz sentido ser uma issue que explica como resolver. Eu criaria uma página na wiki com esta explicação.

2020-11-13 13:41 UTC, noschang commented
> @AlissonSteffens
> @noschang 
> 
> ![image](https://user-images.githubusercontent.com/8836540/99011726-7dd71080-252b-11eb-99f1-aebc7a18f871.png)

Show @AdsonEsteves !

2020-11-13 16:46 UTC, AdsonEsteves commented
@AlissonSteffens
1. antes de finalizar eu pretendo alterar. Isso é só pra poder testar e não precisar ficar gerando commits no master.
2. Foi baseado no mesmo estilo do #421 . Particularmente prefiro assim, já que tbm é uma issue e reune tudo em um lugar só, com a possibilidade de comentários dos usuários. Não sei o que o @noschang pensa.

2020-11-15 19:10 UTC, noschang commented
> @AlissonSteffens
> 
>     1. antes de finalizar eu pretendo alterar. Isso é só pra poder testar e não precisar ficar gerando commits no master.
> 
>     2. Foi baseado no mesmo estilo do #421 . Particularmente prefiro assim, já que tbm é uma issue e reune tudo em um lugar só, com a possibilidade de comentários dos usuários. Não sei o que o @noschang pensa.

@AdsonEsteves e @AlissonSteffens, pra mim tanto faz estar na Wiki ou em uma issue, desde que seja fácil para os usuários acessarem

2020-11-24 21:09 UTC, AdsonEsteves commented
@AlissonSteffens 
@Rafaelfcosta 
@noschang 

Atualizei os links para a nova API.
Também coloquei o novo link para a aba das discussões: https://github.com/UNIVALI-LITE/Portugol-Studio/discussions/886

@noschang também fiz o reporte do #421 como queria:
![image](https://user-images.githubusercontent.com/8836540/100151637-32542900-2e80-11eb-8795-3d10c5a39ab3.png)

2020-11-25 03:42 UTC, AlissonSteffens approved these changes

2020-11-25 03:44 UTC, AlissonSteffens commented
@Rafaelfcosta acho que seria legal adicionar um analytics na API, faz um documento com uma entrada só que é um contador de acessos pros endpoints. O que acha?

2020-11-26 19:16 UTC, merged